version: '2.1'

services:
  nginx:
    image: nginx:1.15-alpine
    restart: always
    volumes:
    - ./nginx/dev.nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/maintenance.html:/maintenance.html
    ports:
    - 5000:80
    depends_on:
    - logs
