version: '2.1'

volumes:
 pg_data: {}

services:
  logs:
    image: gliderlabs/logspout
    environment:
      SYSLOG_HOSTNAME: helpmanual_search
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

  postgres:
    image: postgres:9.6-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
    command: postgres -c fsync=off -c full_page_writes=off -c shared_buffers=512MB -c work_mem=32MB -c max_wal_size=512MB
    volumes:
    - pg_data:/var/lib/postgresql/data
    depends_on:
    - logs

  web:
    build: main
    environment:
      APP_DB_HOST: postgres
      APP_DB_PASSWORD: docker
    depends_on:
    - postgres
    - logs
