#!/usr/bin/env bash
set -e
THIS_DIR=$(dirname "$0")

export VERSION="`git rev-parse --short HEAD`-`date +%Y-%m-%dT%Hh%Mm%Ss`"
echo "VERSION: $VERSION"
echo ""
eval "${THIS_DIR}/compose up -d --build $@"

echo "docker compose up, waiting for container to come up..."
sleep 5
docker ps
